version: '3'
services:
  excel-frontend:
    image: excel-frontend
    build:
      # ./docker/frontend
      context: .
      dockerfile: ./docker/frontend
    environment:
      - PROXY_PASS=http://excel-backend:3000
      - NGINX_PORT=8080
    ports:
     - "8080:8080"
  excel-backend:
    image: excel-backend
    build:
      # ./docker/backend
      context: .
      dockerfile: ./docker/backend
    ports:
      - "3000:3000"
