name: Deploy Docker to Yandex Cloud 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.29.0-focal
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
#       - run: npx playwright install-deps
#       - run: npx playwright install
      - run: npm run build --if-present
      - run: npm test
      # Runs a single command using the runners shell   
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT}} -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts
      - name: Yandex Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DOCKER_HOST }}
          key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.SSH_PORT }}
#           deployment_mode: docker-compose
#           deploy_path: /opt/excel
#           copy_stack_file: false          
#           stack_file_name: docker-compose.yml          
#           args: up -d --build 
          script: |
            sudo -i
            cd /opt/excel/src/tables_p/
            git fetch origin dev
            git reset --hard FETCH_HEAD
            git clean -d -f --exclude secrets
            git pull
            docker-compose -f docker-compose.yml down
            docker-compose build
            docker-compose -f docker-compose.yml up -d
            #cp -f docker-compose.yml ../../docker-compose.yml
      - name: Print Info
        run: echo "Deployed at yandex ayakimkin"
        
